-- Hackathon project submissions
CREATE TABLE IF NOT EXISTS submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  email TEXT,
  discord_id TEXT,
  linkedin_url TEXT,
  telegram_id TEXT,
  tatum_account_id TEXT,
  sui_address TEXT,
  account_id TEXT,
  memwal_agent_id TEXT,
  description TEXT,
  demo_video_url TEXT,
  repo_url TEXT,
  additional_docs TEXT,
  walrus_experience TEXT,
  walrus_friction TEXT,
  social_posts TEXT,
  -- legacy / optional extras
  display_name TEXT,
  team_name TEXT,
  team_size TEXT,
  role TEXT,
  project_title TEXT,
  track TEXT,
  tagline TEXT,
  demo_url TEXT,
  blog_url TEXT,
  deck_url TEXT,
  memory_writes TEXT,
  uses_tatum BOOLEAN DEFAULT false,
  mainnet_confirmed BOOLEAN DEFAULT false,
  how_heard TEXT,
  first_web3_project TEXT,
  anything_else TEXT
);
